name: Post to Twitter (DMM X Bot)

on:
  schedule:
  - cron: '0 11 * * *' # 毎日UTC11時に実行（JSTで20時に実行）に実行
  - cron: '0 3 * * *' # 毎日UTC3時に実行（JSTで12時に実行）に実行
  - cron: '0 22 * * *' # 毎日UTC22時実行（JSTで7時に実行）に実行
  workflow_dispatch: # 手動実行も可

jobs:
  post-tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file from secrets
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> .env
          echo "API_KEY_1=${{ secrets.API_KEY_1 }}" >> .env
          echo "API_SECRET_KEY_1=${{ secrets.API_SECRET_KEY }}" >> .env
          echo "ACCESS_TOKEN_1=${{ secrets.ACCESS_TOKEN }}" >> .env
          echo "ACCESS_TOKEN_SECRET_1=${{ secrets.ACCESS_TOKEN_SECRET }}" >> .env
          echo "BEARER_TOKEN_1=${{ secrets.BEARER_TOKEN }}" >> .env
          echo "SUPABASE_URL_1=${{ secrets.SUPABASE_URL_1 }}" >> .env
          echo "SUPABASE_KEY_1=${{ secrets.SUPABASE_KEY_1 }}" >> .env
          echo "API_KEY_2=${{ secrets.API_KEY_2 }}" >> .env
          echo "API_SECRET_KEY_2=${{ secrets.API_SECRET_KEY_2 }}" >> .env
          echo "ACCESS_TOKEN_2=${{ secrets.ACCESS_TOKEN_2 }}" >> .env
          echo "ACCESS_TOKEN_SECRET_2=${{ secrets.ACCESS_TOKEN_SECRET_2 }}" >> .env
          echo "BEARER_TOKEN_2=${{ secrets.BEARER_TOKEN_2 }}" >> .env
          echo "SUPABASE_URL_2=${{ secrets.SUPABASE_URL_2 }}" >> .env
          echo "SUPABASE_KEY_2=${{ secrets.SUPABASE_KEY_2 }}" >> .env
          echo "API_KEY_3=${{ secrets.API_KEY_3 }}" >> .env
          echo "API_SECRET_KEY_3=${{ secrets.API_SECRET_KEY_3 }}" >> .env
          echo "ACCESS_TOKEN_3=${{ secrets.ACCESS_TOKEN_3 }}" >> .env
          echo "ACCESS_TOKEN_SECRET_3=${{ secrets.ACCESS_TOKEN_SECRET_3 }}" >> .env
          echo "BEARER_TOKEN_3=${{ secrets.BEARER_TOKEN_3 }}" >> .env



      - name: Run tweet bot
        run: python main.py
        
      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-artifacts
          path: |
            debug*.html
            debug*.png
          if-no-files-found: ignore   # ← ファイルが無いときに失敗しない