name: Post to Twitter (DMM X Bot)

on:
  schedule:
   
  - cron: '0 15 * * *' # 毎日UTC15時から18時に実行（JSTで0時から3時に実行）に実行
  workflow_dispatch: # 手動実行も可

jobs:
  post-tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file from secrets
        run: |
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          echo "API_SECRET_KEY=${{ secrets.API_SECRET_KEY }}" >> .env
          echo "ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}" >> .env
          echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" >> .env
          echo "BEARER_TOKEN=${{ secrets.BEARER_TOKEN }}" >> .env
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> .env
          echo "API_KEY_2: ${{ secrets.API_KEY_2 }}" >> .env
          echo "API_SECRET_KEY_2: ${{ secrets.API_SECRET_KEY_2 }}" >> .env
          echo "ACCESS_TOKEN_2: ${{ secrets.ACCESS_TOKEN_2 }}" >> .env
          echo "ACCESS_TOKEN_SECRET_2: ${{ secrets.ACCESS_TOKEN_SECRET_2 }}" >> .env
          echo "API_KEY_3: ${{ secrets.API_KEY_3 }}" >> .env
          echo "API_SECRET_KEY_3: ${{ secrets.API_SECRET_KEY_3 }}" >> .env
          echo "ACCESS_TOKEN_3: ${{ secrets.ACCESS_TOKEN_3 }}" >> .env
          echo "ACCESS_TOKEN_SECRET_3: ${{ secrets.ACCESS_TOKEN_SECRET_3 }}" >> .env

      - name: Run tweet bot
        run: python main.py
